[server]
port = 8080
document_root = "/var/www"

[[mimetypes]]
extension = ".txt"
type = "text/plain"

[[mimetypes]]
extension = ".html"
type = "text/html"

[[mimetypes]]
extension = ".jpg"
type = "image/jpg"

[[mimetypes]]
extension = ".png"
type = "image/png"

[log]
level = "Debug"
destination = "stderr"
