server:
  port: "localhost"
  document-root: /var/www
mimetypes:
  - extension: ".txt"
    type: text/plain
  - extension: ".html"
    type: text/html
  - extension: ".jpg"
    type: image/jpg
  - extension: ".png"
    type: image/png
log:
  level: Debug
  destination: stderr
